# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
      - uses: ghostoy/dingtalk-action@master
        with:
          webhook: "https://oapi.dingtalk.com/robot/send?access_token=36a1e8b0ef6ba7ccddd320cfb9fceae841917ed4850a329aedc52f87d05a5877"
          ksecret: "SECb72bffd2104d07454dc9754a6bf0a9f4fd1e8bf110de7b87d1f5af7a14e0598a"
          msgtype: markdown
          content: |
            {
              "title": "New push",
              "text": "commit: ${{ github.sha }}"
            }
          at: |
            {
              "atMobiles": [
                "13331009010"
              ],
              "isAtAll": false
            }

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          alias ll="ls -alh"
          sudo timedatectl set-timezone "Asia/Shanghai"
          git clone https://github.com/coolsnowwolf/lede
          cd lede
          echo "src-git OpenClash https://github.com/vernesong/OpenClash.git" >> feeds.conf.default
          echo "src-git SSRplus https://github.com/fw876/helloworld"
          sed -i 's/wndr4300_mtdlayout=mtdparts=ar934x-nfc:256k(u-boot)ro,256k(u-boot-env)ro,256k(caldata)ro,512k(pot),2048k(language),512k(config),3072k(traffic_meter),2048k(kernel),23552k(ubi),25600k@0x6c0000(firmware),256k(caldata_backup),-(reserved)/wndr4300_mtdlayout=mtdparts=ar934x-nfc:256k(u-boot)ro,256k(u-boot-env)ro,256k(caldata)ro,512k(pot),2048k(language),512k(config),3072k(traffic_meter),2048k(kernel),121856k(ubi),123904k@0x6c0000(firmware),256k(caldata_backup),-(reserved)/' ./target/linux/ar71xx/image/legacy.mk
          sed -i 's/\.disabled=1/\.disabled=0/' ./package/kernel/mac80211/files/lib/wifi/mac80211.sh
          sed -i 's/\.ssid=OpenWrt/\.ssid=stoneson/' ./package/kernel/mac80211/files/lib/wifi/mac80211.sh
          sed -i "s/set system\.\@system\[-1\]\.hostname='OpenWrt'/set system.@system[-1].hostname='WNDR4300'/" ./package/base-files/files/bin/config_generate
          sed -i "s/set system\.\@system\[-1\]\.timezone='UTC'/set system.@system[-1].timezone='CST-8'/" ./package/base-files/files/bin/config_generate
          sed -i "s/0\.openwrt\.pool\.ntp\.org/ntp1.aliyun.com/" ./package/base-files/files/bin/config_generate
          sed -i "s/1\.openwrt\.pool\.ntp\.org/time1.cloud.tencent.com/" ./package/base-files/files/bin/config_generate
          echo "net.netfilter.nf_conntrack_max=65535" >> ./package/base-files/files/etc/sysctl.d/10-default.conf
          echo "net.ipv4.ip_forward = 1" >> ./package/base-files/files/etc/sysctl.d/10-default.conf
          ./scripts/feeds clean && ./scripts/feeds update -a && ./scripts/feeds install -a
          curl -fsSL https://github.com/chenxinxing/gfw/raw/master/openwrt/config.buildinfo  > .config
          make defconfig && make prereq
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          
      - name: send dingtalk message
        uses: ghostoy/dingtalk-action@master
        with:
          webhook: ${{ secrets.DINGTALK_WEBHOOK}}
          msgtype: markdown
          content: |
            {
              "title": "chenxinxing/helloworld 构建通知",
              "text": "已完成下载。"
            }
          at: |
            {
              "atMobiles": [
                "13331009010"
              ],
              "isAtAll": false
            }

      - name: SSH 连接，设置menuconfig
#       uses: mxschmitt/action-tmate@v1 #在退出连接后不能进行到下一个步骤，所以在实际使用中没有多少价值，只能用于 SSH 连接。
        uses: csexton/debugger-action@master
          
